export enum Permiso {
  VER_CATALOGO = 'VER_CATALOGO',
  GESTIONAR_CARRITO = 'GESTIONAR_CARRITO',
  REALIZAR_COMPRA = 'REALIZAR_COMPRA',
  CARGAR_PRODUCTO = 'CARGAR_PRODUCTO',
  GESTIONAR_PRODUCTOS = 'GESTIONAR_PRODUCTOS',
  ACTUALIZAR_ESTADO_PEDIDO = 'ACTUALIZAR_ESTADO_PEDIDO',
  DAR_ALTA_CLIENTE = 'DAR_ALTA_CLIENTE',
  DAR_BAJA_CLIENTE = 'DAR_BAJA_CLIENTE',
}

export enum EstadoPedido {
  PENDIENTE = 'PENDIENTE',
  PAGADO = 'PAGADO',
  ENVIADO = 'ENVIADO',
  ENTREGADO = 'ENTREGADO',
}

export enum TipoPago {
  TARJETA = 'TARJETA',
  EFECTIVO = 'EFECTIVO',
  TRANSFERENCIA = 'TRANSFERENCIA',
}

export enum TipoUsuario {
  CLIENTE = 'CLIENTE',
  ADMINISTRADOR = 'ADMINISTRADOR',
}

export enum CanalNotificacion {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH = 'PUSH',
}
